spring:
  config:
    activate:
      on-profile: prod
admin:
  password: Admin_123
  username: admin
output_dir: /mnt/c/Users/ADanej/Documents
cmd:
  oprnode: /opt/HPBSM/opr/bin/opr-node.sh -ln -username admin -password Admin_123
  hcconfig: /opt/HPBSM/opr/bin/opr-node-hc-config.sh -user admin -password Admin_123 -list_nodes -all -det
---
spring:
  config:
    activate:
      on-profile: test
admin:
  password: Admin_123
  username: admin
output_dir: /mnt/c/Users/ADanej/Documents
cmd:
  oprnode: /opt/HPBSM/opr/bin/opr-node.sh -ln -username admin -password Admin_123
  hcconfig: /opt/HPBSM/opr/bin/opr-node-hc-config.sh -user admin -password Admin_123 -list_nodes -all -det
---
spring:
  config:
    activate:
      on-profile: dev
admin:
  password: Admin_123
  username: admin
output_dir: c:\\Temp
cmd:
  oprnode: c:\\HPBSM\\opr\\bin\\opr-node.bat -ln -username admin -password Admin_123
  hcconfig: c:\\HPBSM\\opr\\bin\\opr-node-hc-config.bat -user admin -password Admin_123 -list_nodes -all -det
logging:
  level:
    processor: info